FROM node:18.17.1-alpine3.17

WORKDIR /usr/main/sample-angular-nest

COPY ./build_scripts ./build_scripts

RUN sh build_scripts/base_build.sh

ENV npm_config_cache /usr/main/sample-angular-nest/npm_cache

USER public

COPY nginx.conf /etc/nginx

COPY --chown=public:public . .

RUN sh build_scripts/app_build.sh

EXPOSE 80

CMD ["sh", "build_scripts/start_server.sh"]
